Userモデルのテスト実装
great084/twitter_tool pull request #109
Opened 2021-01-30 22:32 UTC by nakamitsu-nozomi

colses #88 
## 目的・概要

Userモデルのテストコード実装
## テスト内容

- 
-
-

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 連絡事項

なし

2021-01-31 01:22 UTC, domi10momo approved these changes
確認しました。OKです。

2021-02-07 01:31 UTC, great084 requested changes
@nakamitsu-nozomi 
遅くなりすみません。
実装したspecの内容は良いと思いますが、modelスペックは`spec/system/users_spec.rb`へ追記するのではなく、`spec/models/user_spec`に記載してください。

2021-02-07 20:56 UTC, nakamitsu-nozomi commented
## 修正

## 修正個所
-  'spec/system/users_spec.rb'から'spec/models/user_spec'に記載

## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正

2021-02-10 08:24 UTC, great084 approved these changes
OKです！

2021-02-14 10:33 UTC, merged