gem, jsライブラリの導入
great084/twitter_tool pull request #11
Opened 2020-11-08 00:33 UTC by nakamitsu-nozomi

## 実装内容

- `pry-byebug`,`pty-rails` ,`pry-doc`を開発環境、テスト環境で導入
- `annotate`導入
- `Rspec` を開発環境、テスト環境で導入。(`rails g rspec:install` 済)
- `devise`,`rails-i18n`,`devise-i18n`,`kaminari`導入
-`dotenv-rails`を導入（`.env`作成済）
-`omniauth-twitter`,`twitter`導入
- `bootstrap`導入
## 参考資料

- デバックツール[共同開発のコード参照]
-Rspec
 - [テストコードの実装（RSpec）](https://arcane-gorge-21903.herokuapp.com/texts/223)

- bootstrap
 - [メッセージ投稿アプリ（その3・Bootstrap）](https://arcane-gorge-21903.herokuapp.com/texts/271)

- omniauth-twitter
 -[【Rails】dotenv-railsの導入方法と使い方を理解して環境変数を管理しよう！](https://pikawaka.com/rails/dotenv-rails)
## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2020-11-08 15:01 UTC, domi10momo commented
gem, ライブラリの選定、導入ありがとうございます。
気になったところ１点コメントいたします。

参考資料にも記載ありますが、`.env`は`.gitignore`に指定し、gitにアップロードされないようにしたほうが宜しいです。
よろしくお願い致します。

2020-11-09 13:34 UTC, great084 requested changes
/log 配下をgit管理対象外にしてください。
あと、昨日のミーティングでお願いした、カレンダー表示するjsライブラリの導入をお願いします。

2020-11-09 13:34 UTC, great084 commented on log/development.log
> +
logファイルがgit管理対象に入ってしまっています。
.gitignoreに、/log配下記載して、git管理対象外にしてください。

2020-11-11 14:13 UTC, great084 approved these changes

2020-11-11 14:14 UTC, great084 commented
@nakamitsu-nozomi 
>　.gitignoreを修正し/logを傘下に入れる際に、.gitignoreをフォルトを参考に大幅に修正し、キャッシュを全削除しました。
確認しました。

2020-11-12 12:45 UTC, merged