AutoTweetテーブルのカラム名変更
great084/twitter_tool pull request #116
Opened 2021-02-14 10:27 UTC by nakamitsu-nozomi

## 目的・概要

AutoTweetテーブルのカラム名変更

## 実装内容

- exclude_repost (int)カラムの追加
- exclude_tweet(int)カラムの削除
-
-

## UI変更概要

- なし

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 連絡事項

なし

2021-02-15 11:00 UTC, domi10momo requested changes
@nakamitsu-nozomi 
ご対応ありがとうございます。申し訳ないのですが、１点修正お願いします。

ツイート投稿日時と再投稿日時が検索対象のため、`exclude_tweet`と`exclude_repost`のカラムを作成したいです。

前回のプルリク では、`auto_tweet.rb`は`exclude_tweet`と`exclude_repost`と設定されていたのですが、`schema.rb`が`exclude_tweet`と`exclude_retweet`となっておりmodelとschemaのカラム名が一致していませんでした。

`auto_tweet.rb`, `schema.rb`共に`exclude_tweet`とexclude_repost`にてカラムの設定をお願いします。

2021-02-20 22:15 UTC, nakamitsu-nozomi commented
closes #112

## 目的・概要
<!--  プルリクエストの目的・概要を記載  -->
AutoTweetテーブルのカラム名変更

## 実装内容
<!-- 実装の技術的な内容を箇条書きで記載 -->
- exclude_repost (int)カラムの追加
- exclude_tweet(int)カラムの削除

## 作成したテーブル

カラム | 型 | 備考
-- | -- | --
user_uid | string |  
tweet_hour1 | integer(0~23) | 00分指定
tweet_hour2 | integer(0~23) | 00分指定
tweet_hour3 | integer(0~23) | 00分指定
tweet_hour4 | integer(0~23) | 00分指定
tweet_hour5 | integer(0~23) | 00分指定
sort_column | string | (favorite_count,retweet_count,tweet_created_at）
order | string | asc or desc
exclude_retweet | integer | 直近xヶ月
exclude_repost | integer | 直近xヶ月
count | integer | 自動投稿時に1回あたりに投稿するツイート件数


## UI変更概要
<!-- UIの変更内容を大まかに記載 -->
- なし


## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正


## 連絡事項
<!-- 本プルリク反映後に運用変更が必要になる場合など記載 -->
なし

2021-02-20 22:52 UTC, domi10momo approved these changes
@nakamitsu-nozomi 
OKです！　ありがとうございます。

2021-02-21 08:44 UTC, great084 approved these changes
確認しました。OKです。

2021-02-21 09:35 UTC, merged