twitterのユーザ認証
great084/twitter_tool pull request #16
Opened 2020-11-11 23:39 UTC by domi10momo

Closes #12 

# 目的
Twitterアカウントにて、ページにログイン、ログアウト機能を実装

# 機能
- Twitterにてログイン
- Twitterアカウントにてログアウト

# userモデル(仮作成)
| カラム名 |  型 | 説明 |
-----------|---|------|
| uid  | string | TwitterのユーザID|
|nickname| string | @以降のハンドルネーム |
|name| string| 名前|
|image| string| アイコン画像|

# 動作確認（初回）

1. rootページからヘッダーの「ログイン」クリック
　ログインしていないため、ページには「ログインしていません」と表示

2.  アプリ認証画面表示

3. rootページにリダイレクト
　ページに「ログイン中」と表示、さらにUserモデルに格納されているユーザデータを表示

次回以降は、ログイン、未ログイン状態によってページ表示が変化する。

# 参考資料
[Railsアプリに簡単なTwitterログインを実装する](https://qiita.com/d0ne1s/items/7a96b835280f55bb5234)

2020-11-13 05:57 UTC, great084 commented
@domi10momo 

ブランチを切るときにmasterからでなはなく、nozomiさんのプルリクマージ前のブランチから切ったと思われるので、
余計な差分が出てしまっています。一度、直近のmasterをマージしていほしいです。

あと、質問ですが、deviseの機能を使わずにログイン・ログアウト機能を実装したという認識でよいでしょうか？

2020-11-15 13:54 UTC, great084 approved these changes
OK

2020-11-15 14:08 UTC, great084 requested changes
db作成完了後に、直近のmasterをマージしてください。

2020-11-16 00:05 UTC, nakamitsu-nozomi reviewed
コードを拝見させて頂きました。Qiitaを参考に綺麗にわかりやすいコードができていると思います。一つ疑問に思ったのことは以下も`link_to`で書けそうだなと思いました。あえてaタグを利用しているのであればそのままでもいいと思います！
```
    <a href="/auth/twitter">ログイン</a>
```

2020-11-16 00:05 UTC, nakamitsu-nozomi commented on app/views/shared/_header.html.erb
> +    <a href="/auth/twitter">ログイン</a>
コードを拝見させて頂きました。Qiitaを参考に綺麗にわかりやすいコードができていると思います。一つ疑問に思ったのことは以下も`link_to`で書けそうだなと思いました。あえてaタグを利用しているのであればそのままでもいいと思います！
```
    <a href="/auth/twitter">ログイン</a>
```

2020-11-16 22:44 UTC, nakamitsu-nozomi commented
ログインリンクの変更を確認致しました。

2020-11-20 20:57 UTC, domi10momo commented
現マスターブランチをマージしました。

.env_sampleを参考にAPIキーを.envに格納してから動作確認お願いします。

# 動作確認（初回）
rootページからヘッダーの「ログイン」クリック
　ログインしていないため、ページには「ログインしていません」と表示

アプリ認証画面表示

rootページにリダイレクト
　ページに「ログイン中」と表示、さらにUserモデルに格納されているユーザデータを表示

次回以降は、ログイン、未ログイン状態によってページ表示が変化する。

2020-11-21 06:16 UTC, domi10momo commented
- herokuにて動作確認
今後のSearchAPIなどの使用も考慮し、URLはgithubには載せない考えです。

- ログイン後のユーザ情報がDB上の最初のユーザを指定していたため、ログインユーザの情報に変更

2020-11-22 12:54 UTC, great084 requested changes
まず動作確認に関して。コードは後ほど確認します。

正常時（ユーザがTwitter認証を許可した場合）→OK
エラー時（ユーザがTwitter認証をキャンセルした場合）→システムエラーが発生するので、エラー処理を追加して、認証にしッパした旨を表示させてください。

2020-11-23 10:07 UTC, domi10momo commented
# 機能追加
- ログインキャンセル時に、ルートURLへ遷移
- その後、ログイン失敗の旨を伝えるメッセージをフラッシュ表示

2020-11-24 00:24 UTC, great084 requested changes
【動作確認】
・cancel時の挙動OKです。

【コード確認】
- `app/views/users/index.html.erb.tmp`,`app/views/users/index.html.erb.tmp`：不要なファイルであれば削除してcommitしてください
- その他、コード内にレビュー結果記載しています。

2020-11-24 00:24 UTC, great084 commented on app/controllers/sessions_controller.rb
> +    if user
Userをfindした結果で、処理を分岐させ、falseの場合はUserインスタンスを作成していますが、この場合以下のようなメソッドを使用することでシンプルに書けると思います。トライしてみてください。
`find_or_create_by`, `find_or_initialize_by`

2020-11-24 13:49 UTC, domi10momo commented on app/controllers/sessions_controller.rb
> +    if user
新しいレコードの場合、nicknameカラムを追加する必要があるため、find_or_initialize_byメソッドを使用しました。
とてもコードがスッキリしました。ありがとうございます。

2020-11-25 00:24 UTC, great084 requested changes
@domi10momo 
確認しました。find_by_initializeを導入することでだいぶスッキ入りしましたね。

削除したsession_controller.rbの def create内の以下の処理は残したほうが良いと思います。
というのは、Twitter側でユーザの認証を行ったにも関わらず、（何らかの理由で）callback後の処理に必要なデータが
欠落していた場合、システムエラーとなるのを防ぎ、エラーの切り分けをできるようにするためです。
なので、redirectに加えてエラーメッセージを表示させてください。

```
    unless request.env['omniauth.auth'][:uid]
      redirect_to root_url
    end
```

あと、コードに関しての以下のレビュー内容も確認お願いします。

2020-11-25 00:24 UTC, great084 commented on app/controllers/sessions_controller.rb
> +    binding.pry
コミットする際にはdebugを外しましょう。
※これは今私が着手しているrubocopを導入することで防げるようになります

2020-11-25 00:24 UTC, great084 commented on app/controllers/sessions_controller.rb
> +    user.update_attributes(nickname: user_data[:info][:nickname])
1.  `update_attributes`は将来廃止対象なので、`update`を使用しましょう。
 ※実行ログを注意深く見ると以下のwarningがあります。

```
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1 (please, use update instead)
```

2. userを「find_or_initializeした後、値を更新する」という２つの処理を連続して実施する場合には、メソッドチェーンを使うとコードがスッキリします。

```suggestion
    user = User.find_or_initialize_by(XXXX).update(XXXX)
```

2020-11-26 03:57 UTC, domi10momo commented
### 以下2つの機能の修正
- binding.pryの削除
- 何らかの理由でユーザ認証のリクエスト値が欠損した場合の処理

### 確認
`Sessions_controller`の`user_data = request.env['omniauth.auth']`の後に`binding.pry`を挿入
user_data = nilを代入し、処理続行
rootページにリダイレクトし、エラーメッセージが表示されること確認

2020-11-26 08:38 UTC, great084 approved these changes
確認しました！OKです。

2020-11-27 00:11 UTC, nakamitsu-nozomi reviewed
ローカル環境にて動作確認を行いました。
.envにAPIキー等を入れることで、通常のログインログアウトは正常に動いていることを確認しました。
しかし、
ブラウザにて、`ログイン`　→　キャンセル（cancel)　→twitter_tool_appに戻る(Return to Twiiter_app)
を押すと、401 Authorization Required が出ました。
<img width="1440" alt="スクリーンショット 2020-11-27 9 01 59" src="https://user-images.githubusercontent.com/67478234/100397918-a0bb0600-308f-11eb-81dd-e9ca9122ca59.png">
<img width="1440" alt="スクリーンショット 2020-11-27 9 03 58" src="https://user-images.githubusercontent.com/67478234/100397995-07d8ba80-3090-11eb-8b37-4afbb4ebb710.png">


この問題は私のローカルに問題があるのでしょうか。

2020-11-27 00:25 UTC, domi10momo commented
動作確認ありがとうございます。
現在、私のローカルで確認しましたが、問題なく動きました。

まず、DeveloperアカウントからコールバックURLの設定を確認いただけますか。
[Twitterログイン認証で404(forbidden)や401(Unauthorized)エラーがでたときの対処法](https://qiita.com/ngron/items/1f9d315e5ec0f4ae6098)

2020-11-27 00:25 UTC, nakamitsu-nozomi approved these changes
先ほどのレビューを削除しました。
キャンセル動作も含めて動作確認できました。

2020-11-27 00:47 UTC, merged