DB定義
great084/twitter_tool pull request #19
Opened 2020-11-16 22:12 UTC by nakamitsu-nozomi

# 目的
DB定義しテーブル、カラムを作成
インデックスを張る

# 実装内容
- Userモデル作成
- Tweetモデル作成
- Mediumモデル作成
-Tweetモデルにインデックスを貼る
- 各モデルにバリテーションを記載

# userモデル
| カラム名 |  型 | 説明 |
-----------|---|------|
| uid  | string | TwitterのユーザID|
|nickname| string | @以降のハンドルネーム |

# Tweetモデル
| カラム名 |  型 | 説明 |インデックス有無 |
-----------|---|------|------|
|  tweet_created_at | datetime | ツイート投稿作成日時|○ |
|tweet_id| string | twitterに登録されているID |× |
|text| string | ツイート内容 |○  |
|retweet_count| int | リツイート数 | ○ |
|favorite_count| int|  いいね数| ○ |
|user_id| int | ツイートした人のID（FK) | 外部キーなので自動生成|
|tweet_flag| boolean | 再投稿したかを示すフラッグ | ○ |
|retweet_flag| boolean | リツイートしたかを示すフラッグ | ○ |

# Mediumモデル
| カラム名 |  型 | 説明 |
-----------|---|------|
| tweet_id  | int | どのツイートの画像か紐づける(FK)|
|media_url| string | ツイート画像URL |

# 動作確認（初回）
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
####その他
- rails c のサンドバックモードにて、カラムの追加、バリテーションが機能しているか確認。

# 参考資料
[データベースにindexを張る方法
](https://qiita.com/seiya1121/items/fb074d727c6f40a55f22)

2020-11-17 13:15 UTC, domi10momo requested changes
確認しました。
userとtweet, tweetとmediumモデルは1対多のため、モデルにhas_manyを追加お願いします。
また、userデータが消えるとその人のtweetデータが消えるように、あるtweetデータが消えるとそのツイートのmediumデータが消えるように下記サイト参考にdependentも追加お願いします。
[[Rails] has_manyおよびbelongs_toへのdependent: :destroyの設定について](https://qiita.com/after4649/items/1ad419dc705f807735e0)

2020-11-18 23:11 UTC, great084 requested changes
@nakamitsu-nozomi 
以下のindexだけ修正お願いします。
その他は問題ありません。

2020-11-18 23:11 UTC, great084 commented on db/migrate/20201116140204_add_index_to_tweet.rb
> +    add_index :tweets,:text
tweetsテーブルのtextは検索対象項目ではないので、indexは不要だと思います。

2020-11-18 23:49 UTC, nakamitsu-nozomi commented on db/migrate/20201116140204_add_index_to_tweet.rb
> +    add_index :tweets,:text
レビューありがとうございます。
指摘箇所を修正致しました。
確認の程、よろしくお願い致します。

2020-11-19 06:02 UTC, great084 approved these changes
修正点確認しました。OKです。

2020-11-19 14:00 UTC, domi10momo approved these changes
すみません、、確認OKです。

2020-11-19 23:03 UTC, merged