投稿したツイートのエンゲージメント取得
great084/twitter_tool pull request #20
Opened 2020-11-22 08:02 UTC by nakamitsu-nozomi

Closes #17 

# 目的
ツイートを取得し、パラメータを取得する

# 実装内容
- boolean型カラムのnull false制約を解除
- TweetテーブルとMediumテーブルにseedデータ投入し、ツイート一覧ビューを作成
- アップロード画像をgit管理下から排除
- gem twitterを用いて、いいね数、リツイート数、投稿内容、投稿日時、リツイート有無、投稿画像　を取得しビューに表示。

# スクリーンショット
<img width="1440" alt="スクリーンショット 2020-11-22 16 35 26" src="https://user-images.githubusercontent.com/67478234/99898373-4e22c800-2ce4-11eb-9ccb-908db9cb2733.png">

# 参考資料
- [The Twitter Ruby Gem](https://rubydoc.info/gems/twitter/frames)
- [Twitter API (Ruby)](https://qiita.com/mosa_siru/items/8ab1093417d5976237fc)
- wikiのTwitterAPI 取得パラメータ一覧
- [yhara/gist:3087849](https://gist.github.com/yhara/3087849)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

# 備考
　- @hisadomiさんのツイート認証ブランチをマージした際にコンフリクトすると感じたので、ルーチングを`   get '/tweets', to: 'tweets#index'`にしている
- ページネーションはエンゲージメント取得をした際に上手く機能しなくなったので一度削除しました。（後で再実装します）
- 取得したエンゲージメントはDBに格納していません。現時点では、ブラウザでリロードするたびに、tweetデータを取ってきて表示する仕組みになってます。

2020-11-24 15:04 UTC, domi10momo requested changes
コードはよく見れていませんが、動作実行して現状感じたことをまとめます。
- リツイート、再投稿有無の欄（一番左）が、ページ内にリツイート、再投稿履歴がある場合と全く無い場合で大きさが変わっています。そのため、他の欄も大きさが変化しています。
ページ遷移した場合に見た目がズレるため、修正お願いします。

2020-11-26 23:10 UTC, nakamitsu-nozomi commented
## 修正点
- booleanカラムにnull制約再追加、バリテーション変更
- DBにデータがある前提で一覧ページのビューを作成
- ツイート詳細ページ実装
- 一覧ページのテーブルの行（横軸）を固定してスクロール実装
- テーブルのの幅と高さを固定



# 動作確認
- 一覧ページ
- リツイート・ツイートボタン欄：ボタン幅固定カラム幅も固定
　- 投稿内容は長文の場合、省略表示
　-  投稿詳細ページへのリンク実装
　- 画像の数に限らずカラムの高さと幅固定
- 詳細ページ
　- 画像の数に限らずカラムの高さと幅固定

`.seedデータを挿入してから動作確認お願いします。`

## 備考欄
　デベロッパーツールを開いた際に、`Uncaught Error: Bootstrap's JavaScript requires jQuery`とエラーが出ていたので、
jQueryを導入し、app/views/layouts/application.html.erb　にjQueryを追加する項目を記載しエラーを解決しました。

<img width="1440" alt="スクリーンショット 2020-11-27 8 06 14" src="https://user-images.githubusercontent.com/67478234/100396190-8e3cce80-3087-11eb-897a-4a8858d43697.png">

2020-11-27 01:13 UTC, domi10momo requested changes
表示動作は確認できました。コードについてレビューいたします。

1. 「ユーザ認証」のブランチをマージしたため、コンフリクトが発生しています。

2. `application.scss `にて以下が見られます。
　- インデント ずれ
　- 括弧の位置ずれ
　- 余分な改行

3. tweetsの`index, show `のビューファイルスタイル指定（提案）
width, heightなどのスタイル指定がビューファイル内とscss内に混在しています。
可能な限り、classを指定し、scss内からスタイル指定を呼び出す運用に統一した方が良いのではないでしょうか。

4. tweetsの`index, show `のビューファイルのリファクタリング
- リツイート、再投稿済みのボタン表示(index, show共通）
- 各カラムの値表示(特にshow)

テーブルのタグの関係で1つの処理を表すために行数が多くかさんでいます。
投稿日時、投稿内容、リツイート数、いいね数の表記は1つのファイルを使用し、ローカル変数を作成したファイルに渡すことで呼び出すことができる気がします。（他にもできそうであればリファクタリングお願いします）

パーシャルの使用方法　参考

[Rails　パーシャル(部分テンプレート)へローカル変数を渡したいとき](https://qiita.com/takannporo/items/a8ff93109afc3bc3bab4)

以上内容の解消、修正お願いします。

2020-11-29 14:25 UTC, great084 requested changes
rubocop使用と書いてますが、私が別プルリクエストで実装したrubocopの設定（※）が反映されていないようです。
※：railsアプリ初期作成ファイルや、自動生成ファイルに対してはrubocopのチェック・自動修正を行わない。

そのため、不要なファイルまで修正されているため、一度rubocop実行前までcommitを戻してほしいです。

その他指摘は、以下のコード部分を確認してください。

2020-11-29 14:25 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    @tweets = Tweet.order(id: :desc).includes(:media).page(params[:page]).per(PER_PAGE)
これだと、ログインしたユーザ以外のデータも取得してしまうので、ユーザを指定してください。

2020-11-29 14:25 UTC, great084 commented on app/views/layouts/application.html.erb
>    </head>
boostrarp, jqueryの読み込みは、webpackerを使用して、`application.js`でrequireしてください。
この、application.html.erbには記載しないでください。
参考：https://arcane-gorge-21903.herokuapp.com/texts/216

2020-11-30 04:17 UTC, nakamitsu-nozomi commented
## 修正点
-  rubocop使用前にコミット戻し、masterを再マージ
- `application.scss `を修正
-  一覧・詳細ページをリファクタリング
- ログインユーザーの投稿のみを一覧ページに表示
- ログインユーザーの投稿でない詳細ページにアクセス時のリダイレクト実装
- application.html.erbのjQuery記載を削除


## 動作確認
- ログインユーザーの投稿のみを一覧ページに表示
- ログインユーザーの投稿でない詳細ページにアクセス時のリダイレクト

## 備考欄
- rubocopはまだ使用してません。

2020-11-30 12:18 UTC, great084 reviewed
修正内容確認しました。
以下の点確認・修正お願いします。

2020-11-30 12:18 UTC, great084 commented on app/views/layouts/application.html.erb
>    </head>
現状まだ、bootstrapをCDNから読み込んでいるので、削除してください。

2020-11-30 12:18 UTC, great084 commented on app/models/medium.rb
>  end
carrierwaveは使用しないことになったので、この設定は外しておいてください。

2020-12-01 02:12 UTC, nakamitsu-nozomi commented
## 修正点
-  carrierwave削除
- bootstrapの読み込み方法修正

2020-12-02 15:12 UTC, domi10momo approved these changes
動作確認できました。私は、以下修正を頂ければ一旦マージしても大丈夫です。

1. 新たなマージによるコンフリクト解消

2.application.scss 57~69行目

.table-showの中にth
.show_media_row
.show_tweet_mediaの3つで1つなのか

.table-showの中にth, .show_media_row, .show_tweet_mediaがあるのか

が一眼でみて、分かりづらいです。インデント修正か括弧位置の修正をお願いします。

2020-12-03 22:56 UTC, nakamitsu-nozomi commented
## 修正点
-  sass削除
- bootstrapの読み込み方法修正
- kaminariのbootstrap３をbootstrap４へ変更

2020-12-04 03:16 UTC, great084 requested changes
@nakamitsu-nozomi 
確認しました。
画面で一覧表示・詳細表示することができました。

細かい以下の点だけ修正願います。

2020-12-04 03:16 UTC, great084 commented on app/views/tweets/index.html.erb
> +          <% tweet.media.each do |media| %>
一覧画面に表示させるメディア（画像or動画）は最初の１つだけです。

`tweet.madia.each`とすると、全てのメディアを表示させることになるので修正願います。

2020-12-04 03:16 UTC, great084 commented on db/seeds.rb
> +    media_url: File.open('./app/assets/images/sample.png')
`media_url`はメディアのURLの文字列なので、urlを設定してください

2020-12-04 03:16 UTC, great084 commented on db/seeds.rb
> +    user_id: 1,
`user_id: 1`としてしまうと、idが1のUserが存在していない場合は処理エラーとなります。
seedファイルは自己完結する必要があるので、前処理としてUserを検索or作成する処理を入れたほうが良いと思います。

2020-12-05 02:21 UTC, nakamitsu-nozomi commented
## 修正点
-  seedにてユーザー作成を記載し、ユーザーに紐づいたツイート作成を実装
- ツイート一覧ページにて画像を一枚のみ表示
- ツイート一覧ページのツイート表示順を日付順に変更

2020-12-05 15:24 UTC, great084 approved these changes

2020-12-06 00:25 UTC, merged