Fix/query sent time
great084/twitter_tool pull request #34
Opened 2020-12-05 15:47 UTC by domi10momo

## 目的・概要

取得する時間は日本時間だが、APIを取得しに向かう時間が標準時のため、ツイート取得時間のクエリを調整する必要があった。

## 実装内容

- `DateTime.now.gmtime`にて取得時間を標準時に合わせることで、ツイート取得時間の調整が不要

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

2020-12-06 05:07 UTC, nakamitsu-nozomi approved these changes
日本時間でデータ取得出来ていることを確認しました。

2020-12-06 14:31 UTC, great084 requested changes
@domi10momo 
ソース見たのですが、先祖返りしているようです。

[時差のためdate_toの時間を9時間調整する必要をなくす機能実装](https://github.com/great084/twitter_tool/pull/34/commits/54ba8290be535e3620aff46b822fe73d6b1e6dd5)
のコミットの内容が正しいですよね？

2020-12-06 14:50 UTC, great084 requested changes
確認しました。以下の部分だけ修正願います。

2020-12-06 14:50 UTC, great084 commented on app/models/tweet.rb
> +          date_to: datetime.ago(0.years).strftime("%Y%m%d%H%M"),
`.ago(0.years)`って不要では？

2020-12-06 14:50 UTC, great084 commented on app/models/tweet.rb
> +          date_from: datetime.ago(1.years).strftime("%Y%m%d%H%M")
rubocopでも指摘されたと思いますが、`1.years`ではなく、`1.year`ですね。

2020-12-08 01:39 UTC, great084 approved these changes
OKです。

2020-12-08 03:02 UTC, merged