検索機能の実装
great084/twitter_tool pull request #37
Opened 2020-12-06 04:14 UTC by nakamitsu-nozomi

## 目的・概要
ツイート一覧ページの検索機能

## 実装内容
### 検索機能の実装
- 再投稿済の投稿(ラジオボタン）
- リツイート済の投稿(ラジオボタン）
- 投稿日(ラジオボタン）
- リツイート数（数値入力）
- いいね数（数値入力）

## UI変更概要

- bootstrapのtableを使用

### 画面キャプチャ

<img width="1440" alt="スクリーンショット 2020-12-06 13 11 59" src="https://user-images.githubusercontent.com/67478234/101271261-b1245c80-37c4-11eb-8408-f7615d074b35.png">

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
-(Rubyon Rails で検索機能を作ろう（ransack）) [https://qiita.com/nojinoji/items/e1b174220da8c81a1756]

2020-12-06 12:54 UTC, domi10momo requested changes
> 検索ボタンを上下中央寄せ出来ない

上下中央寄せしても良いですが、スマホで使用することを考えると、条件選択の下に検索ボタンがあったが良いのでは？と感じましたがいかがでしょうか。

また、検索ボタンもbootstrapを使用して欲しいです・・・
ちなみに、bootstrapのd-flex align-items-center justify-content-centerにて要素の上下左右寄せができるようです。（なぜかrowspan= "5"が反映されませんが）

> 投稿日時のみ選択した際に、ラジオボタン が押したままにならない。

どういう処理が走っているのか掴めていないので、解決法はまだ分かりません。上の2つとの違いといえば、@nowがページ遷移前後で異なるため、同じ値と認識されずどのボタンもチェックが入ってないのでは？という予想です。

> ラジオボタンのところは下記のようにリファクタリングできるかなと思ったが、うまく出来ませんでした。

可能かもしれませんが、変数をたくさん渡す必要があるため、個人的にはそこまでしなくても良いのでは？という考えです。逆に、いいね数、リツイート数はできるのではないでしょうか。

別途、確認です。
- コンフリクトが発生しているため、解消お願いします。
- rubocopを使用すると、tweets_controller.rb の8行目が長いと怒られています。解消お願いします。
（その他の私が実装した部分のrubocopの指摘は、コンフリクト解消すれば、消えると思います。）

2020-12-08 15:13 UTC, great084 requested changes
@nakamitsu-nozomi 
確認遅くなりました。

まず、稼働確認した結果だけお伝えします。
- 2ページ目以降を表示したタイミングで、検索項目入力してボタン押しても、検索が動かないです
- 「再投稿済の投稿」、「リツイート済みの投稿」の"指定なし”というボタンですが、ワイヤーフレームには存在しません。
  また、"指定なし"と、"再投稿/リツイートを含む"との違いもよくわかりません。（含むの場合、再投稿/リツイートのみの挙動になってないですかね？？）

- 投稿日時を指定して検索すると、指定内容が消えてしまうので、保持してほしいです。

2020-12-12 03:17 UTC, nakamitsu-nozomi commented
## 修正点
- コンフリクト解消
- 絞り込みボタンにbootstrap導入
- 2ページ目以降で検索できないバグを修正
- ラジオボタン 機能するように修正


## 動作確認
- 2ページ目以降で検索できる
- 日付検索時ラジオボタン 機能するように修正



## 備考欄
 絞り込みボタンを`rowspan`を使ってセル結合したのですが、マージン調整や、`d-flex align-items-center justify-content-center`を使うと、rowspanが機能しなくなることを修正できませんでした。

2020-12-13 15:26 UTC, great084 commented
@nakamitsu-nozomi 

検索条件を見ていて、「含める/含めない」の検索はラジオボタンは良くなかったですね。
チェックボックスべきでした（私が作成したワイヤーフレームの失敗です）
別途Issueを起票するのでこのまま進んでください。

>絞り込みボタンをrowspanを使ってセル結合したのですが、マージン調整や、d-flex align-items-center justify-content-centerを使うと、rowspanが機能しなくなる

`d-flex`を指定するとflex要素になってまい、table要素で指定可能なrowspanが適用できるなくなるためです。
table要素の場合、以下のスタイルを指定すると、上下左右中央に配置できますよ。

```
    vertical-align: middle;
    text-align: center;
```

あと、

2020-12-14 21:44 UTC, domi10momo approved these changes
確認しました。修正箇所動作問題ありません。
rubocopにて１箇所指摘が入っているため、そこを直していただければOKです。

2020-12-15 00:21 UTC, nakamitsu-nozomi commented
rubocop指摘箇所修正しました。

2020-12-15 05:24 UTC, great084 approved these changes

2020-12-15 13:55 UTC, merged