100件（1回の取得最大件数）以上のツイート取得
great084/twitter_tool pull request #40
Opened 2020-12-07 23:55 UTC by domi10momo

Closes #31 

## 目的・概要

1回の最大取得件数が100件のため、指定期間内に100件以上ツイートがあった場合、取得漏れが生じるのを改善

## 実装内容

- 1回目のレスポンス取得時の"next"パラメータを用いて次の100件を新たにリクエスト
- ひろみちさんのコードを参考に、クエリのパラメータ形式をハッシュにて指定
-

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- [ひろみちさんのコード](https://github.com/great084/twitter_tool/wiki/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89(Twitter-API))

- [twitter developer](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/premium-search#Pagination)

## 連絡事項

特になし

2020-12-08 17:07 UTC, great084 requested changes
私の環境では、fullarchive使えず、tweetの件数が足らなかったため、30day＆かみさとさんのアカウントで確認しました。３００件超でも問題なく取得できました。

動作内容はOKだと思いますが、コーディングの書き方でいくつか修正をお願いします。

2020-12-08 17:07 UTC, great084 commented on app/models/tweet.rb
require文不要だと思います。railsでデフォルで読み込まれているので。

2020-12-08 17:07 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    def next_token_exist?(response, query_params)
`?`がつくメソッドは、返り値がtrue / falseというのがrubyのネーミイングルールです。単純に`next_token'でよいのでは？

前回指摘漏れだと思いますが、`extended_entities_exist?`も同様です。

2020-12-08 17:07 UTC, great084 commented on app/models/tweet.rb
> +      data.merge!({ "next": query_params[:next].to_s }) unless query_params[:next].nil?
```suggestion
      data.merge!({ "next": query_params[:next].to_s }) if query_params[:next]
```
あえてunlessを使う必要ないと思います。

2020-12-09 11:16 UTC, domi10momo commented
ご指摘ありがとうございます。いずれも、賛成のため取り入れさせていただきます。
修正し、動作確認、rubocop,rspecのエラーないこと確認しております。

2020-12-10 01:50 UTC, nakamitsu-nozomi reviewed
- 私の環境では動作確認を行いましたが、なぜか2020/10/06 以降(100件以降）のツイートが取得できません。即近のツイート情報が更新できることは
確認できております。
写真の通り環境はfullachiveになってるとは思うので、他にローカル環境に問題があるのかなとおものですが、アドバイスお願い致します。
.envには、BEARER_TOKENと以下は記入してます。
```
PLAN = fullarchive
LABEL = TwitterToolApp
```
<img width="1440" alt="スクリーンショット 2020-12-10 10 18 11" src="https://user-images.githubusercontent.com/67478234/101710100-2f8a4280-3ad4-11eb-8d29-47c60b16307b.png">

2020-12-10 01:50 UTC, nakamitsu-nozomi commented on app/controllers/tweets_controller.rb
> +      response["results"].each do |res|
- 私のアカウントの場合、1年以上前にツイートがないのですが、1年以上前のボタンを押した際に、この箇所で`undefined method `each' for nil:NilClass`とエラーが出ました。

2020-12-10 11:41 UTC, domi10momo commented
修正しました。ご確認お願いします。
nozomiさんの環境ではなく、私のコードの問題と思われます。

以下、修正、追加しましたのでご確認お願いします。
- 現在~1年前までのツイートが取得できること
- 取得が0件だった場合に、アラートを出し期間指定画面に戻るよう修正

2020-12-10 23:06 UTC, nakamitsu-nozomi approved these changes
動作確認行いました。１００件以上の取得、データがない場合の表示を確認しました。
rubocopとrspecにてエラーがないことも確認致しました。

2020-12-12 01:04 UTC, great084 approved these changes
遅くなりました。
修正箇所確認しました。

2020-12-12 09:03 UTC, merged