oauth認証のアクセストークン,シークレットをDBに格納
great084/twitter_tool pull request #45
Opened 2020-12-10 14:05 UTC by domi10momo

## 目的・概要

Twitterの投稿を行う場合、twitterユーザのアクセストークンが必要となるため、
認証時にtoken, secretを取得し、DBに保存する

## 実装内容

- request.envからtoken ,secret取得
- ログイン時にUsersテーブルへtoken, secretを格納

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- https://qiita.com/gin0606/items/9f71645d485249684e9f

## 動作確認

rails consoleにて1回目のログイン前はtoken, secret = nil, 1回ログイン後は、token, secret共に文字列のトークンが入っていること確認

2020-12-11 08:10 UTC, great084 requested changes
動作確認OKです。
コードはちょっと指摘あるので確認＆修正お願いします。

2020-12-11 08:10 UTC, great084 commented on app/controllers/sessions_controller.rb
> +      secret: user_data.credentials.secret
Mashの指定方法を統一しましょう。
hashのように"[:info]"とするか、
メソッド呼び出しのように".credentials"とするのか。

2020-12-12 09:51 UTC, domi10momo commented
了解です。抜けてました。ありがとうございます！
修正しましたので、再度確認お願いします。

2020-12-12 10:08 UTC, great084 approved these changes

2020-12-12 10:08 UTC, great084 commented
> 了解です。抜けてました。ありがとうございます！
> 修正しましたので、再度確認お願いします。

確認しました。OKです。

2020-12-13 07:26 UTC, nakamitsu-nozomi approved these changes
動作確認しました。問題ないと思います！

2020-12-13 08:23 UTC, merged