Feature/sort
great084/twitter_tool pull request #47
Opened 2020-12-13 23:56 UTC by nakamitsu-nozomi

closes #33 

## 目的・概要
ツイート一覧ページのソート機能

## 実装内容
### ソート機能の実装
- リツイート数でソート
- いいね数でソート

### 画面キャプチャ

<img width="1440" alt="スクリーンショット 2020-12-14 8 34 18" src="https://user-images.githubusercontent.com/67478234/102027867-412c5c80-3dea-11eb-9d40-4978ae5407f2.png">

## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正

## 参考資料
-　[Rubyon Rails で検索機能を作ろう（ransack](https://qiita.com/nojinoji/items/e1b174220da8c81a1756)

2020-12-14 15:21 UTC, domi10momo requested changes
修正、確認お願い致します。

2020-12-14 15:21 UTC, domi10momo commented on app/views/tweets/index.html.erb
> +      <th scope="col"><%= sort_link(@q, :favarite_count, "いいね数", { default_order: :desc }, { class: "Editlink" }) %></th>
`:favarite_count`となっているため、「いいね数」のソートが動作していません。修正お願いします。

2020-12-14 15:21 UTC, domi10momo commented on app/assets/stylesheets/application.scss
> +
【確認】調べたら、&は親セレクタの参照をしていると知りました。&内の子セレクタも親要素と変化が無いため、親要素のみの記述でも変わらない気がします。&にて指定されているのは何か考えがあるのでしょうか？
考えがあれば、特に修正は必要ありません。

2020-12-15 00:30 UTC, nakamitsu-nozomi commented on app/assets/stylesheets/application.scss
> +
@domi10momo 
修正致しました。
指摘箇所なのですが、
```
  &:hover {
    text-decoration: none;
    color: black  }
```
を抜いてしまうと、リンクを触った時の色が変わらないため、 &:hover だけ記述したままになってます。

2020-12-15 00:32 UTC, nakamitsu-nozomi commented
### 修正箇所
- いいね数ソート機能部分タイポ修正し、バグ解消
- リンクの色指定のscss修正
- 黒色の色味変更

2020-12-16 13:25 UTC, great084 approved these changes
OKです。

2020-12-16 22:56 UTC, nakamitsu-nozomi commented
コンフリクトを解消しました。

2020-12-17 10:44 UTC, domi10momo approved these changes
動作、コード確認OKです。

2020-12-18 06:19 UTC, merged