選択したツイートのリツイート機能実装
great084/twitter_tool pull request #49
Opened 2020-12-14 14:37 UTC by domi10momo

closes #38 

## 目的・概要

`tweets/show`ページから、「リツイートする」ボタンを押した際のリツイート処理を実装

## 実装内容

- twitter gemのretweetメソッドを使用
- ツイート、ユーザ情報が取得できない場合、リツイートができない場合の例外処理実装

## UI変更概要

- ツイート詳細画面のボタンが2つとも「再投稿する」となっていたため、1つを「リツイートする」に変更
- リツイート成功、失敗時にフラッシュメッセージ表示

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- https://qiita.com/resignater/items/8a31a08801b899495ab0

## 連絡事項

なし

2020-12-16 22:42 UTC, nakamitsu-nozomi reviewed
動作確認しました。コードもシンプルで良いと思います。フラッグを変更するところまで書いても良いのかなと感じました。

2020-12-17 06:18 UTC, great084 requested changes
動作確認しました。
リツイート自体は問題なく動きました。
フラッシュメッセージの表示とてもわかり易くて良いです。
あとは画面設計に乗っ取りをmodalで表示後に、送信するように変更してください。
（+nozomiさんのコメントにある、flagの更新もお願いします）

コードはとてもシンプルに纏まっていてわかりやすいです。一部エラー時の画面遷移先だけ修正をお願いします。

2020-12-17 06:18 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    redirect_to tweets_path, danger: "リツイートに失敗しました #{e}"
失敗したときに、一覧画面へ遷移してしまうので、成功時と同様に詳細画面へ遷移願います。

2020-12-17 15:41 UTC, domi10momo commented
- flagの更新
- エラー時の遷移リンク先変更
- リツイート編集画面のモーダル表示

以上３点修正しました。ご確認お願い致します。
また、コメントの後に存在ツイートのURLを貼ったらコメント付きのリツイートとなりました。
そのため、リツイートするためのメソッドとしてはツイート投稿機能と同じ`client.update`を使用しています。

2020-12-19 07:01 UTC, nakamitsu-nozomi approved these changes
動作確認しました。モーダルにもなっていて素晴らしいと思います。
コードも見やすくていいと思います。

2020-12-19 15:18 UTC, great084 reviewed
動作確認OKです。
Twitter側でもきちんと引用ツイートで表示されました。

一点質問です。
差分にマージした他のプルリク内容が出てきているのですが、どのようにマージしましたか？
masterをマージしてますか？

2020-12-19 15:18 UTC, great084 commented on app/controllers/tweets_controller.rb
> +      client.update("#{params_retweet[:add_comments]}  #{old_tweet_url}")
質問です。
元TwitterのURLを含めて投稿すると、引用ツイートになるということでしょうか？

2020-12-19 18:17 UTC, domi10momo commented
@great084 ひろみち
お手数かけ、申し訳ございません。再度ご確認お願い致します。

1ファイル内のコードが100行以上だとrubocopの指摘が入ります。
`tweet.rb`と`tweets_controller.rb`でメソッドを調整しようとしてもどちらかが超えてしまいます。
そのため、helper内にテーブル格納処理を移行して、rubocopの指摘を防いでいます。
このような方法で宜しいでしょうか・・・他に案があればお願いします。

2020-12-20 01:51 UTC, great084 commented
@domi10momo 

> 1ファイル内のコードが100行以上だとrubocopの指摘が入ります。
> `tweet.rb`と`tweets_controller.rb`でメソッドを調整しようとしてもどちらかが超えてしまいます。
> そのため、helper内にテーブル格納処理を移行して、rubocopの指摘を防いでいます。
> このような方法で宜しいでしょうか・・・他に案があればお願いします。

helperに移行するというのは、本来やるべきではないので、100行以上が必要ならばそのルールを無効化すれば良いと思います。
rubocopの結果出てきたエラーを`rubocop.yml`に記載して`  Enabled: false`を設定すれば無効化できます。（もしくはもう少し条件を200行とかゆるくするか）

2020-12-20 07:30 UTC, domi10momo commented
@ ひろみち
ご教示ありがとうございます。helperは使うべきではないのですね。rubocop設定修正し、controllerへメソッド戻しています。
ご確認お願い致します。

2020-12-20 09:02 UTC, great084 commented
@domi10momo 
> ご教示ありがとうございます。helperは使うべきではないのですね。rubocop設定修正し、controllerへメソッド戻しています。
> ご確認お願い致します。

helperの役割はviewの補助機能として使うためなので、今回のようにAPIの接続処理を記述するべきではないです。
分割するとしたら別途Issueにあげたようにlib化するのが良いかと思います。
rubocopの設定変更内容がリポジトリに上がっていないので、pushお願いします。

> > 元TwitterのURLを含めて投稿すると、引用ツイートになるということでしょうか？
> 
> はい、そのようです。
> 実際のTwitterアプリでも引用リツイートは、「ツイートする」ボタンを押してリツイートします。
> そのため、動作としてはツイートの投稿機能を使用する方向で合っているのではと考えました。
> 
> 参考（PHPですが)
> (https://munokuno.com/other/tips/tweet-using-api/)

ありがとうございます！とても参考になります。

2020-12-20 09:23 UTC, domi10momo commented on .rubocop.yml
>  # private/protected は一段深くインデントする
rubocop設定ファイルの確認です。
`.rubocop.yml`の変更であればプッシュしています。

2020-12-20 15:59 UTC, great084 approved these changes
OKです。

2020-12-20 15:59 UTC, great084 commented on .rubocop.yml
>  # private/protected は一段深くインデントする
確認しました。

2020-12-20 21:03 UTC, merged