[機能追加]選択した投稿を再投稿する #39
great084/twitter_tool pull request #51
Opened 2020-12-15 13:47 UTC by nakamitsu-nozomi

## 目的・概要

選択した投稿を再投稿する機能を実装

## 実装内容

- 再投稿ボタンを押すと、再投稿編集ページに移動
- 再投稿編集ページで編集後、投稿ボタンを押すと再投稿完了
- 再投稿できたら、再投稿フラッグをtrueに変更
- 140字以上の投稿、空欄投稿の場合の例外処理実装
## UI変更概要

-  再投稿編集ページ、投稿詳細ページでもフラッシュ実装

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
-(Rubyで簡単なTwitter クライアントをつくる)[https://qiita.com/shimisunet/items/c3a0b93fb13fa82ed8be]
## 連絡事項

- 画像投稿は実装できていません
- モーダル表示になっていません
- rubocopでtweetコントローラ、post_createアクションが長いと注意されていますが、最後に修正しようかなと考えています。

2020-12-18 23:54 UTC, domi10momo requested changes
動作確認中、異常な箇所があったためコメントいたします。

2020-12-18 23:54 UTC, domi10momo commented on app/controllers/tweets_controller.rb
>  end
access_tokenとaccesstoken_secretにdeveloperツールにて取得されたキーを使用されていると思います。
developerアカウント（A）以外のアカウント（B)で再投稿した場合を試しました。
結果、Bが再投稿操作をしてもAのアカウントにて再投稿した動作となりました。改善をお願いします。

2020-12-19 15:36 UTC, great084 requested changes
一旦現時点のコードをチェックしましたので確認してください。

2020-12-19 15:36 UTC, great084 commented on app/controllers/tweets_controller.rb
> +      if @client.update("#{@tweet.text}\r")
２回`client.update`をコールしているので、前者は不要です。

2020-12-19 15:36 UTC, great084 commented on app/views/tweets/post_new.html.erb
> +  <div><%= f.submit %></div>
画面上で必須チェック＆最大文字数チェックを実装しましょう。

2020-12-19 15:36 UTC, great084 commented on app/controllers/tweets_controller.rb
> +          redirect_to new_tweet_path, flash: { aler: "指定した期間内にデータはありませんでした。" }
誤った修正だと思います。

2020-12-20 07:03 UTC, nakamitsu-nozomi commented
closes #60
バグレポートを作成しました。確認の程、よろしくおねがい致します。

2020-12-20 14:10 UTC, nakamitsu-nozomi commented
closes  #39 
# 修正点

## 修正内容
<!-- 実装の技術的な内容を箇条書きで記載 -->
- 重複コード削除
- post_createアクション内の変数名変更
- ログインユーザーのaccess_tokenとaccesstoken_secretを指定
- 前回作成の再投稿フォームを削除、モーダルフォーム作成
- rubocop設定変更

- ## UI変更概要
<!-- UIの変更内容を大まかに記載 -->
-  特になし

## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正

## 参考資料
-[Rubyで簡単なTwitter クライアントをつくる](https://qiita.com/shimisunet/items/c3a0b93fb13fa82ed8be)
## 連絡事項

- 画像投稿は実装できていません（別issue作成）

2020-12-20 14:12 UTC, nakamitsu-nozomi commented on app/views/tweets/post_new.html.erb
> +  <div><%= f.submit %></div>
修正しました。

2020-12-20 14:13 UTC, nakamitsu-nozomi commented on app/controllers/tweets_controller.rb
> +          redirect_to new_tweet_path, flash: { aler: "指定した期間内にデータはありませんでした。" }
再修正しました。

2020-12-20 14:13 UTC, nakamitsu-nozomi commented on app/controllers/tweets_controller.rb
> +      if @client.update("#{@tweet.text}\r")
修正しました。

2020-12-20 14:13 UTC, nakamitsu-nozomi commented on app/controllers/tweets_controller.rb
>  end
修正しました。

2020-12-20 15:40 UTC, domi10momo approved these changes
ありがとうございます。動作確認できました。

2020-12-20 15:41 UTC, great084 approved these changes
動作確認OKです。
コードは一点軽微な修正があるので直しておいてください。（私は再レビュー不要です）

2020-12-20 15:41 UTC, great084 commented on app/views/tweets/_tweet_modal.html.erb
> +        <h5 class="modal-title" id="label1">リツイートする</h5>
modalタイトルが「リツイートする」になっているの修正してください。

2020-12-20 22:29 UTC, nakamitsu-nozomi commented on app/views/tweets/_tweet_modal.html.erb
> +        <h5 class="modal-title" id="label1">リツイートする</h5>
修正しました。

2020-12-20 23:09 UTC, nakamitsu-nozomi commented
closes  #39 
# 修正

## 修正内容
<!-- 実装の技術的な内容を箇条書きで記載 -->
- マスター（リツイート機能）をマージ
- 再投稿機能にフラッシュ表示導入。
- 再投稿機能の例外処理記載方簡潔化


 ## UI変更概要
<!-- UIの変更内容を大まかに記載 -->
-  再投稿機能にフラッシュ表示導入。

## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正

## 参考資料
-[Rubyで簡単なTwitter クライアントをつくる](https://qiita.com/shimisunet/items/c3a0b93fb13fa82ed8be)
## 連絡事項

- 画像投稿は実装できていません（別issue作成）

2020-12-21 00:26 UTC, great084 commented
OKです。マージ後の動作も確認できています。

2020-12-21 05:33 UTC, merged