[機能追加]1回の取得ツイート数、総取得ツイート数表示
great084/twitter_tool pull request #61
Opened 2020-12-20 09:40 UTC by domi10momo

## 目的・概要

- ツイート取得件数の表示

## 実装内容

- ツイート取得時・・・APIレスポンスが返った後、json内の要素数を加算
- 一覧画面表示時・・・`tweets/index`アクション実行時、ログインユーザのツイート件数を取得

## UI変更概要

- ツイート取得時・・・取得したツイート件数をフラッシュメッセージにて表示
- 一覧画面表示時・・・今まで取得したツイートの合計件数を一覧画面上部に表示

### 画面キャプチャ

![スクリーンショット 2020-12-20 18 33 30 2](https://user-images.githubusercontent.com/35606852/102709929-14001280-42f2-11eb-96e4-e71ea2675be5.png)

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- なし

## 連絡事項

まだ、モックアップは修正できていません。
ローカル環境の確認、件数表示箇所に違和感は無いかご確認お願い致します。

2020-12-20 14:30 UTC, domi10momo commented
解釈の違いが合ったようなので、再度内容をまとめます。

## 目的・概要
検索件数の表示


## 実装内容
- ツイート取得時・・・APIレスポンスが返った後、json内の要素数を加算
- 一覧画面表示時・・・検索をかけた後の該当ツイート数を表示

## UI変更概要
ツイート取得時・・・取得したツイート件数をフラッシュメッセージにて表示
一覧画面表示時・・・検索該当ツイート件数を検索画面下部に表示

## 画面キャプチャ
他のアカウントの方のツイートにてリツイート数を変化させて確認
![50](https://user-images.githubusercontent.com/35606852/102715773-f7c49b80-431a-11eb-94c1-7ef9d8ffbd19.png)
![64](https://user-images.githubusercontent.com/35606852/102715776-f98e5f00-431a-11eb-865b-12fb4dce69ca.png)

2020-12-20 23:49 UTC, nakamitsu-nozomi approved these changes
動作確認しました。
良いと思います。

2020-12-21 05:03 UTC, great084 requested changes
動作確認しました。
一点気になったのは、データ保存した際にフラッシュで表示される「XX件のツイートを取得しました」というメッセージです。
すでに取得済みで、件数が変わっていない場合にも関わらず、件数が増えたよような表示は違和感を感じました。

その他コードの細かい部分はコメントしています。

2020-12-21 05:03 UTC, great084 commented on .rubocop.yml
> +
別プルリクエストで対応した内容が差分として出てきています。確認をお願いします。

2020-12-21 05:03 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    @q = user_tweets.ransack(params[:q])
メソッド化するのも良いですが、リレーションを使って以下のようにするのはどうでしょうか？
```suggestion
    @q = current_user.tweets.ransack(params[:q])
```

2020-12-21 05:03 UTC, great084 commented on app/views/tweets/index.html.erb
> +<h2>検索：<%= @q.result(distinct: true).count %>件</h2>
"検索結果"ですね。

2020-12-23 00:07 UTC, domi10momo commented on .rubocop.yml
> +
コンフリクト解消する際に、コードが重複していたようです。ありがとうございます。

2020-12-23 00:07 UTC, domi10momo commented on app/controllers/tweets_controller.rb
> +    @q = user_tweets.ransack(params[:q])
メソッド一つ消えるのはありがたいです。取り入れます。

2020-12-23 13:14 UTC, great084 approved these changes
OKです。

2020-12-23 15:13 UTC, merged