APIの処理を外部モジュール化
great084/twitter_tool pull request #68
Opened 2020-12-22 13:31 UTC by domi10momo

## 目的・概要

TweetのモデルファイルにAPIの処理を記載していたため、API処理を別モジュールへ移行

## 実装内容

- ツイート取得処理・・・リクエストのレスポンスを返すまでの処理
- 再投稿処理・・・ツイートを再投稿するまでの処理
- リツイート処理・・・ツイートを引用リツイートするまでの処理

以上、3つの処理コードを新規作成する`app/lib/twitter_api.rb`へ移行する。

## UI変更概要

- 

### 画面キャプチャ

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- 

## 連絡事項

nozomiさんのransack処理を参考に、ツイート取得の際の期間指定方法を変更しようと考えています。
30day, fullarchiveのプランを切り替えて使用したい場合など、御注意のほどお願い致します。

- ツイート取得期間指定箇所変更
（以前）`tweets/new`で選択したボタンに文字列を付与、コントローラへ返す
　　　　返した文字列の内容によって、`tweet.rb`にて期間指定
（現在）`tweet/new`内で期間を値として付与、コントローラのストロングパラメータを取得した時点でfrom,toの期間が取得可能

2020-12-23 14:44 UTC, great084 requested changes
対応ありがとうございます。
まず、API関連の処理を外部ファイル化したことで、modelがとてもスッキリしました！
加えて、今までcontoroller⇔model間を処理が行ったり来たりしていたのが、api libのメソッドを一発呼んで返り値を取るというシンプルな関係性になりました。

大枠はバッチリだと思います。
よりコードを見やすくするために、細かい点を指摘させてもらいましたので確認ください。

2020-12-23 14:44 UTC, great084 commented on app/lib/twitter_api.rb
> +class TwitterApi
インスタンスを作成せず単純にメソッドの集まりなので、classではなく、moduleでよいのでは？

2020-12-23 14:44 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    search_params = params_search
この処理は不要では？

以下の`search_params`の部分を`params_search`にしてしまえば問題ないと思います。
```
res_status, response = TwitterApi.fetch_tweet(search_params)
```

2020-12-23 14:44 UTC, great084 commented on app/controllers/tweets_controller.rb
> +  end
`@datetime`はviewで時刻を取得するためと想定しています。
であれば、helperの出番です、日付関連のヘルパーを作って、この処理及びリファクタリング後のviewに設定している、以下などの記述もまとめて定義するとviewもcontrollerもシンプルになります。
```
@datetime.ago(1.year).strftime("%Y%m%d%H%M")
```

2020-12-23 14:44 UTC, great084 commented on app/lib/twitter_api.rb
> +      headers = fetch_headers
この処理も不要かと思います。後の処理で`headers`を使っているところに、直接`fetch_headers`を設定すれば良いとです。

また、メソッド名も`fetch_headers`より、単純かつ明確に`http_headers`としたほうが良いかと。
※fetchは外部リソースからデータを読み込むときに使います。まさしくfetch_tweetのような時。

2020-12-23 14:44 UTC, great084 commented on app/lib/twitter_api.rb
> +      [res_status, response]
ここも、`res_status`,`response`をそれぞれ設定せずに、`status_in_code(api_response)`, `JSON.parse(api_response.body)`を直接返り値に設定してあげれば、見やすくなるかと。

2020-12-23 15:25 UTC, domi10momo commented on app/controllers/tweets_controller.rb
> +    search_params = params_search
@great084 
ご確認ありがとうございます。loop内でnextパラメータを付与するため、APIリクエストをparams_searchにした場合、パラメータが初期化され、nextパラメータが無くなると考えていますがいかがでしょうか。

2020-12-24 06:37 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    search_params = params_search
@domi10momo
あ、たしかにloop内で読んでるので初期化されますね。
このままで大丈夫です！
ただ、`params_search` , `search_params`という言葉は混乱するので、わかりやすい言葉に変更してもらえると・・

2020-12-24 12:07 UTC, domi10momo commented
@great084 
数点ご指摘ありがとうございます。修正していますのでご確認お願い致します！

2020-12-27 12:22 UTC, great084 approved these changes
遅くなりすみません。
確認しました！OKです。
とても読みやすいコードになりました！

2020-12-27 14:23 UTC, nakamitsu-nozomi reviewed
ツイート取得、再投稿機能にてバグが発生しているように思います。
再度動作確認お願い致します。
再投稿機能に関しては、私の元コードが原因のようで、@hisadomiさんの書き方に修正した方が良さそうですね、、
すみません、いい書き方が浮かばないですが、、

2020-12-27 14:23 UTC, nakamitsu-nozomi commented on app/controllers/tweets_controller.rb
> +    binding.pry
binding.pryは消していいと思います！

2020-12-27 14:30 UTC, nakamitsu-nozomi reviewed
私の環境では再投稿機能やツイート取得部分でバグが発生しているように感じます。
再度動作確認のほど、お願い致します。

再投稿機能に関しては、私のコード再投稿コードとの差分が原因かなと思います、、、@hisadomiさんお書き方に統一すべきかなと思いました。私にはすぐに解決法を見つけるこはできませんでした、、、すみません。

2020-12-28 09:37 UTC, domi10momo commented
@nakamitsu-nozomi 
ご確認ありがとうございます。データの受け渡しがretweetからうまくできていなかったようです。
再投稿、リツイート機能については問題解消していると思われます。再度ご確認お願いします。

ツイート取得機能についてですが、私の方では動作に問題はありません。
どのような問題が発生しているのでしょうか？

2020-12-30 00:49 UTC, nakamitsu-nozomi approved these changes
動作確認しました。コードも確認しました。
先日発生していたエラーは、マイグレーションファイルの変更が原因であったので、解決致しました。

2020-12-30 09:17 UTC, merged