ツイート取得上限件数の指定
great084/twitter_tool pull request #72
Opened 2021-01-04 11:52 UTC by domi10momo

## 目的・概要

- 使用するAPIリクエスト数をユーザ側にてコントロールするため、取得件数の上限指定を行う。

## 実装内容

- ワイヤーフレームの修正
　https://app.diagrams.net/#G146chVVB_E7TbtY6VZ1mPcCP7WFedRxUd

- ツイート取得期間指定時に、上限件数指定の追加

## UI変更概要

- 期間指定の下に、上限件数指定をセレクトボックスにて追加

### 画面キャプチャ

<img width="1249" alt="上限指定" src="https://user-images.githubusercontent.com/35606852/103532381-7fd7a300-4ece-11eb-9090-956b72f27821.png">

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料

## 連絡事項

2021-01-06 02:26 UTC, great084 requested changes
@domi10momo 
動作確認はOKです。
コードに関して、何店か改善をお願いできますでしょうか。
100とか10といった定数は、ハードコーディングするのではなく、定数として宣言してほしいです。

2021-01-06 02:26 UTC, great084 commented on app/views/tweets/new.html.erb
> -</div>
divの閉じタグがなくなっています。

2021-01-06 02:26 UTC, great084 commented on app/models/tweet.rb
> +class RemaingNumber
保存件数をクラスにしたのはとても良いと思います。
ただ、可読性の面からファイルをtweetクラスから外出しにしたほうが良いですね。

2021-01-06 02:26 UTC, great084 commented on app/models/tweet.rb
> +  end
100という定数ですが、他の箇所でもハードコーディングされていますが、変更されることを想定して、外出しにしてはどうでしょうか。

2021-01-08 00:40 UTC, nakamitsu-nozomi approved these changes
動作確認しました。
わかりやすいとコードで良いと思いました。

2021-01-08 01:30 UTC, domi10momo commented
@great084 
アドバイス点、修正しました。ご確認お願い致します。

2021-01-08 17:17 UTC, great084 approved these changes
OKです。

2021-01-09 10:40 UTC, merged