APIエラー時のログ出力
great084/twitter_tool pull request #84
Opened 2021-01-13 14:24 UTC by domi10momo

## 目的・概要

ユーザ起因ではないエラーの際にログを残し、原因を追えるようにする。

## 実装内容

- logger.debug
  search, repost, retweet時のAPIのシステムエラー時に適応

## UI変更概要

### 画面キャプチャ

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- https://docs.ruby-lang.org/ja/latest/method/Logger/i/debug.html

## 連絡事項

2021-01-15 00:41 UTC, nakamitsu-nozomi approved these changes
動作確認しました。
良いと思います。そして勉強になりました。

質問なのですが、ログインの時はlogger.debugは必要ないのでしょうか。

2021-01-15 05:47 UTC, great084 requested changes
ありがとうございます。
ローカル環境でログが出力されていること確認しました。

1. エラー内容だけでなく、エラーコードも出力してほしいです。
2. ログレベルがdebug (いわゆる0)になってっているので、errorにしてほしいです。
    ※現状は本番環境でもdebugも出力されますが、本来本番環境にはdebug文は出力されるべきではなく、今後ログレベルを引き上げたときにも出力されるようにするため

★参考
https://railsguides.jp/debugging_rails_applications.html#%E3%83%AD%E3%82%B0%E3%81%AE%E5%87%BA%E5%8A%9B%E3%83%AC%E3%83%99%E3%83%AB

2021-01-15 15:38 UTC, domi10momo commented
@nakamitsu-nozomi  @great084 
ご確認ありがとうございます。
エラーコードの出力、各環境設定にログのレベルを設定しました。

また、ログイン機能もlogger使用しようと試したのですが、正常に行かず悩み中です。
策がありましたら教えていただきたく思います。

### 悩んでいる点
- 変数`user_data[:uid]`が異常でもrescueには進まない
（ログインができないだけでcurrent_userが設定されていない場合のroot_urlに戻るため、エラーは発生せず）

- また、上記のため、ログイン不可のflashメッセージが表示されず、rspecが通らない

### `session_controller.rb の create`
- 現状master
```
  def create
    user_data = request.env["omniauth.auth"]
    if user_data[:uid]
      user = user_table_update(user_data)
      log_in(user)
      redirect_to root_url
    else
      redirect_to root_url, danger: "ログインできませんでした。もう一度ログインしてください"
      # flash[:alert] = "ログインできませんでした。もう一度ログインしてください"
    end
  end
```

- エラー出力のため、rescueを用いたコード
```
  def create
    user_data = request.env["omniauth.auth"]
    user = user_table_update(user_data)
    log_in(user)
    redirect_to root_url
  rescue StandardError => e
    put_api_error_log("login", status, e)
    redirect_to root_url, danger: "ログインできませんでした。もう一度ログインしてください"
  end
```

2021-01-18 02:39 UTC, great084 commented
@domi10momo 

昨日お話したとおり、Twitterのアカウント認証は、レスポンスとして明確にエラーが返ってくるわけではないので、自アプリ内でエラーハンドリングを行う必要があります。（つまり`rescue StandardError => e`を定義してもヒットしない）

現状`if user_data[:uid]`が、実質的なエラー判定なので、else ブロックにログ出力してあげれば今回の要件は満たせます。

なお、きちんと(?)エラー発生させて、エラー処理をしたいということであればraiseでエラーを意図的に発生させて、それをキャッチするという書き方もできます。

- 参考
```
 def create
    user_data = request.env["omniauth.auth"]
    raise StandarError "リクエストの返り値が正しく有りません" if user_data[:uid]
      #正常な処理
    rescue StandarError
      ＃エラー処理（ログ出力）
  end
```

2021-01-18 22:45 UTC, domi10momo commented
@great084 @nakamitsu-nozomi 
ありがとうございます。実装修正しました。
`user_data`がnilの場合と`user_data[:uid]`がnilの場合で挙動が違ったため、2つログ出力記載しています。
ご確認お願いします。

2021-01-20 13:39 UTC, great084 requested changes
実装OKだと思います。
configのログレベルに関して一部変更お願いしたいので、対応おお願いします。

2021-01-20 13:39 UTC, great084 commented on config/environments/production.rb
> +  config.log_level = :error
51行目に log_levelの記述があるので、そちらを上書きしてください。

2021-01-20 13:39 UTC, great084 commented on config/environments/development.rb
> +  config.log_level = :error
開発環境のログレベルはdebugのままにしてもらえますか。開発時にdebugレベルの内容も確認するので。

> ログレベルがdebug (いわゆる0)になってっているので、errorにしてほしいです。
この私のコメントがいまいちでしたね。正しくは「**logger文の**ログレベルをerrorにしてほしい」といいう意味でした。

2021-01-20 13:39 UTC, great084 commented on config/environments/test.rb
> +  config.log_level = :error
こちらはOKです。

2021-01-21 13:26 UTC, domi10momo commented
@great084 
ありがとうございます。
修正し、development環境でdebugログ出力できること確認できました。

### 別件で修正
tweet取得の際、期間指定しなかった場合、システムエラーとなるため、修正
（Unpermited　Parameter を削除するタスクの実装時に間違えたと思われます。すみません。）

2021-01-22 06:25 UTC, great084 approved these changes
OKです。

以下の指摘だけ対応漏れているので対応しておいてください。
https://github.com/great084/twitter_tool/pull/84/files#r560964438

2021-01-22 12:11 UTC, domi10momo commented
@great084 
すみません、51行目の内容について勘違いしていました。
ログ出力レベル変更しています。ご確認お願い致します。

2021-01-23 06:38 UTC, domi10momo commented
@great084 

> OKです。

> 以下の指摘だけ対応漏れているので対応しておいてください。
> https://github.com/great084/twitter_tool/pull/84/files#r560964438

OKありがとうございます。修正したため、merge致します。

2021-01-23 06:39 UTC, merged