ログイン画面のパス変更
great084/twitter_tool pull request #87
Opened 2021-01-17 11:47 UTC by nakamitsu-nozomi

## 目的・概要

## 実装内容

-　ログイン画面のパスをroot_path からusers_pathへ変更
-　tweet_userアクションのリダイレクト先をroot_path からusers_pathへ変更
-  

## UI変更概要

- なし

### 画面キャプチャ

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 連絡事項

2021-01-18 03:07 UTC, great084 requested changes
動作確認OKです。
コードもログインのパス、ビューも意図した配置になっていると思います。

追加で更にきれいにするためのコメントをしましたので確認ください。

2021-01-18 03:07 UTC, great084 commented on app/controllers/tweets_controller.rb
> +  before_action :tweet_user, only: %i[show search retweet post_create new]
`new`アクションも対象に加えたのですね goodです！
同様に`index`アクションも対象にして、`index`アクション内のユーザ判定も削除できませんか？

そして、すべてのアクションがtweet_userメソッドを実行する事になったら、only ~は不要になるのではないでしょうか？

2021-01-18 03:07 UTC, great084 commented on config/routes.rb
>  end
良い機会なので、ルーティングもきれいにしましょう。
tweetsリソースに対する定義が散らばっているので、まとめてほしいです。

2021-01-19 13:25 UTC, domi10momo commented
@nakamitsu-nozomi 
現状、動作確認しました。ひろみちさんのアドバイス修正後、再度確認いたします。

2021-01-21 10:49 UTC, nakamitsu-nozomi commented on app/controllers/tweets_controller.rb
> +  before_action :tweet_user, only: %i[show search retweet post_create new]
`index`アクションのみtweet_userメソッドを解除したのは、以下の理由です。
```
現在の仕様ではユーザーが最初にアプリを使う時に、root_path→users_pathにリダイレクトされることで、ログイン画面表示される時仕様になっています。

tweet_userをbefore action に入れると、「ログインしてください」とフラッシュがログイン画面表示されてしまいます。

```
この動作を防ぐために、indexアクションでは別でリダイレクト処理を書きました。

この対処法としましては、それとも他に方法があればヒントいただきたいです。
よろしくお願いいたします。

2021-01-21 10:53 UTC, nakamitsu-nozomi commented
##  修正
- tweetsに関するルーティングを整理

2021-01-22 06:34 UTC, great084 commented on app/controllers/tweets_controller.rb
> +  before_action :tweet_user, only: %i[show search retweet post_create new]
未ログイン状態でroot_pathにアクセスしても、「ログインしてください」のフラッシュ表示されても良いと思います。

2021-01-22 07:03 UTC, great084 approved these changes
> tweetsに関するルーティングを整理
確認しました！ 良いと思います。

※リツイートと再投稿で、urlの持ち方が違うのが気になりましたが、今回はこれで大丈夫です。

2021-01-23 23:09 UTC, nakamitsu-nozomi commented
##  修正

## 実装内容
<!-- 実装の技術的な内容を箇条書きで記載 -->
- 再投稿時のパスを"tweet/repost"に変更
- 再投稿メソッド名をpost_createからrepostに変更
- tweet_userのbefore_actionを変更
- masterをマージ
## UI変更概要
<!-- UIの変更内容を大まかに記載 -->
- なし



## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正
- [ ] 
## その他

私の方で動作確認をしましたが、再投稿部分はメソッド内を若干修正したので動作確認をお願い致します。

2021-01-24 00:01 UTC, domi10momo approved these changes
@nakamitsu-nozomi 
ログイン、ログアウト、再投稿問題ありません。
OKです。

2021-01-24 00:01 UTC, domi10momo commented on app/controllers/tweets_controller.rb
> +  before_action :tweet_user, only: %i[show search retweet post_create new]
画像が見えていないのですが、最初にアプリを使う時＝最初にusers/indexを呼び出した時　という認識で宜しいでしょうか？
before_actionにindex入れてみましたが、動作変わらない気がしたため確認です。

2021-01-24 02:18 UTC, nakamitsu-nozomi commented
わかりづらく申し訳ありません。
> 画像が見えていないのですが、最初にアプリを使う時＝最初にusers/indexを呼び出した時　という認識で宜しいでしょうか？
before_actionにindex入れてみましたが、動作変わらない気がしたため確認です。

最初にアプリを使う時＝最初にusers/indexを呼び出した時　です。
その時の画面は以下です。
<img width="1440" alt="スクリーンショット 2021-01-24 11 16 18" src="https://user-images.githubusercontent.com/67478234/105619406-cd905d00-5e35-11eb-8d94-1d617d8335d0.png">

2021-01-24 03:14 UTC, great084 approved these changes
@nakamitsu-nozomi 

確認しました。
再投稿のpath, routes定義も直していただきありがとうございます。
OKです。

2021-01-24 03:35 UTC, merged