タイムラインを表示
great084/twitter_tool pull request #91
Opened 2021-01-17 15:36 UTC by nakamitsu-nozomi

## 目的・概要

ツイート一覧画面にログインユーザーのタイムラインを表示
## 実装内容

- ツイート一覧画面にログインユーザーのタイムラインを表示
- スマホ時はタイムラインは表示しない

## UI変更概要

### 画面キャプチャ

<img width="1440" alt="スクリーンショット 2021-01-18 0 12 53" src="https://user-images.githubusercontent.com/67478234/104847698-13748f00-5925-11eb-8760-df142ecd29b2.png">
## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料

## 連絡事項

2021-01-18 03:26 UTC, great084 requested changes

2021-01-18 03:26 UTC, great084 commented on app/views/tweets/index.html.erb
> +<div class="col-md-8  mx-auto">
col-md-9ではなく、8にしたのはなぜでしょうか？
あと、`md`(>768px）だと、メインのツイート一覧が崩れてしまうので、`lg`(>1024px)で表示のほうが良いかと思いました。

2021-01-19 13:19 UTC, domi10momo commented
@nakamitsu-nozomi 
動作確認できました。問題ありません！

2021-01-19 13:26 UTC, domi10momo commented
> @nakamitsu-nozomi
> 動作確認できました。問題ありません！

2021-01-19 13:28 UTC, domi10momo approved these changes
@nakamitsu-nozomi 
githubの操作を誤り、コメント欄がひどいことになり、申し訳ありません。
動作確認できました。問題ありません。

2021-01-21 09:58 UTC, nakamitsu-nozomi commented on app/views/tweets/index.html.erb
> +<div class="col-md-8  mx-auto">
マージンの関係でcol-md-9だと横に並ばなかったので、８に設定していました。
マージンを調整しcol-lg-9で横並びになるように変更しました。

2021-01-21 10:00 UTC, nakamitsu-nozomi commented
closes #92 
## 修正
<!--  プルリクエストの目的・概要を記載  -->
タイムラインをlg(>1024px)で表示


## UI変更概要
<!-- UIの変更内容を大まかに記載 -->
- タイムラインをlg(>1024px)で表示
- ツイート一覧テーブルのUI微調整


### 画面キャプチャ
<!-- UIの変更後の画像を入れる（UIに変更があった場合） -->
<img width="1440" alt="スクリーンショット 2021-01-21 18 56 36" src="https://user-images.githubusercontent.com/67478234/105335024-e53fc980-5c1a-11eb-9c2a-4c29f025a794.png">


## 稼働確認チェック
- [x] ローカル環境での動作確認
- [x] rspecの実行＆エラーなし
- [x] rubocopの実行＆コード修正

2021-01-22 07:08 UTC, great084 approved these changes
OKです！

2021-01-23 22:11 UTC, merged