前回のクエリを引き継いでツイートを取得できるようにする
great084/twitter_tool pull request #93
Opened 2021-01-17 15:42 UTC by domi10momo

## 目的・概要

API取得制限に引っかかった場合などに、前回の取得の続きから取得できるようにする。

## 実装内容

- 前回のクエリがある場合、"前回の続きから取得する"ボタンを表示する
- 指定取得数に達し、まだ指定期間内に取得していないツイートがある場合、クエリとnextトークンパラメータをsessionに保存する
- nextトークンがない場合、sessionをdeleteする

## UI変更概要

- ツイート取得ボタンを変更

### 画面キャプチャ

## 前回のクエリが保存されていない場合
<img width="436" alt="通常" src="https://user-images.githubusercontent.com/35606852/104847860-939af480-5925-11eb-8b92-15700f23ce96.png">

## 前回のクエリが保存されている場合
<img width="465" alt="前回クエリ" src="https://user-images.githubusercontent.com/35606852/104847871-a0b7e380-5925-11eb-9ebb-9461df9bc3f4.png">

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料

## 連絡事項

2021-01-18 13:31 UTC, great084 requested changes
@hisadomi
動作確認しました。いいですね！
あとは画面UIを改善したいのと、コードが分かりにくい点を直せたらなと思います。

インターネット上にフォームのデザイン例はたくさんあるので、見ながら直して貰えればと思います。

画面UIの分かりづらい点
- ボタンが二つ並んでいますが、選択肢表示 → 前回の続きボタン → 新たな選択肢ボタン と情報が入れ子になっている
- 前回の続きとあるが、「前回」ってなに？と感じる

2021-01-18 13:31 UTC, great084 commented on app/controllers/tweets_controller.rb
> +    return if search_params.instance_of?(String)  # 入力値が異常な場合 HTML文がsearch_paramsに返されるため
この処理は画面入力値のチェックをしているとするならば、search_paramsの返り値で判断するのではなく、パラメータのチェックを実装すべきです。（そして、エラーチェックの後はredirectではなく、renderのほうが良いです）

2021-01-18 13:31 UTC, great084 commented on app/controllers/tweets_controller.rb
> +      return condition_params if params[:commit] == "新しい条件を指定して取得する" && params[:period]
さすがに日本語文書で判定するのは・・・

2021-01-20 21:10 UTC, domi10momo commented
すみません、もう少し修正加えます。

2021-01-21 12:48 UTC, domi10momo commented
@great084  @nakamitsu-nozomi 
おつかれさまです。ひろみちさんのご指摘実装途中で躓いているため、途中報告です。

> この処理は画面入力値のチェックをしているとするならば、search_paramsの返り値で判断するのではなく、パラメータのチェックを実装すべきです。（そして、エラーチェックの後はredirectではなく、renderのほうが良いです）

パラメータが異常だった場合、`render :new`を表示するコードに修正しました。
アプリ内のボタンでの操作は正常に動作します。

しかし、newページの内容が表示されているものの、URLがsearchのパスです。
そのため、ページ自体の更新ボタンを押すとエラーが発生します。
パスをnewに変更する方法はあるでしょうか。



## その他、実装完了機能

> 画面UIの分かりづらい点
> 
> - ボタンが二つ並んでいますが、選択肢表示 → 前回の続きボタン → 新たな選択肢ボタン と情報が入れ子になっている
> - 前回の続きとあるが、「前回」ってなに？と感じる

1.  `前回未取得のツイート`を期間指定のラジオボタン に追加
2. 前回取得できなかった期間を表示してどの期間のツイートを取得するか明記
<br>

> さすがに日本語文書で判定するのは・・・

ラジオボタン 追加により、contorollerへ渡す値を"before_query"として解消

2021-01-22 07:43 UTC, great084 commented
@hisadomi

> パラメータが異常だった場合、`tweets_controllerのsearchアクション内`で`render :new`を表示するコードに修正しました。
> しかし、newページの内容が表示されているものの、URLがsearchのパスです。
> そのため、ページ自体の更新ボタンを押すとエラーが発生します。
> パスをnewに変更する方法はあるでしょうか。

現状の画面遷移の方法だとないです。あるとすればformで非同期通信を使用する場合かね。
ブラウザのベージ更新はフォーム送信系ではうまく行かないことが多いので、考慮しなくてもいいかなと思いました。

> 
> ## その他、実装完了機能
> 
> 1. `前回未取得のツイート`を期間指定のラジオボタン に追加
> 2. 前回取得できなかった期間を表示してどの期間のツイートを取得するか明記

もし画面レイアウトで悩んでいるようでしたら、ワイヤー直してそれを見るでも良いですよ。

> 
> > さすがに日本語文書で判定するのは・・・
> 
> ラジオボタン 追加により、contorollerへ渡す値を"before_query"として解消

了解です。

2021-01-22 10:00 UTC, great084 commented
ちなみに、ラジオボタンのチェックを画面で実装しておけば、バックエンドでエラーパターンは少なくなりすね。

2021-01-22 12:26 UTC, domi10momo commented
@great084 
デザイン面に関して、今まであまり考えたことが無かったためワイヤーフレームのご確認、ご指摘いただけると助かります。
現状のプルリク のワイヤーフレームがこちらです。
https://app.diagrams.net/#G146chVVB_E7TbtY6VZ1mPcCP7WFedRxUd

検索画面のWebデザインを例にして考えました。
①様々な取得条件を指定して、「検索する」ボタンにて検索を行うサイトが多いこと
②1つのラジオボタンに情報を詰め込みすぎるのは良くないと思いますが、どのツイートを取得するか分かるための方法

として、リンクのワイヤーフレームの構成としています。ご確認お願いします。

2021-01-29 17:06 UTC, domi10momo commented
@great084 @nakamitsu-nozomi 
ワイヤーフレームに沿ってデザイン修正しました。
ワイヤーフレームと異なる点として、

- **「条件を指定して取得」「前回の続きから取得」の左側のラジオボタン はつけていません**
➡︎　そのラジオボタン を押してどのような処理を行うのかイメージが湧きにくかったです。

- **「取得ツイート上限件数」のラベル、ボタンを中央に配置**
➡︎　「前回の続きから取得」のラジオボタン を選択した場合も上限件数の設定を行いたいため。

<br>
また、2つ目の「取得ツイート上限件数」のラベルをcardで囲うべきかについて質問です。

 **card有り・・・見た目のバランスは整っている
 card無し・・・期間指定の項目だけが枠で囲われているため、分かりやすい**

現在のプルリク はcard無しです。どちらが宜しいでしょうか。
このほかにも案が有りましたら教えていただけると助かります。

**1. card有り**
<img width="1247" alt="cardあり" src="https://user-images.githubusercontent.com/35606852/106303831-f2555c00-629d-11eb-998b-54d900bbbba3.png">

**2. card無し**
<img width="1248" alt="card無し" src="https://user-images.githubusercontent.com/35606852/106303846-faad9700-629d-11eb-952e-16e39b430e19.png">

2021-01-30 10:02 UTC, great084 commented
@hisadomi
お疲れさまです！
試行錯誤して取り組まれていてとても良いと思います。

> card無し・・・期間指定の項目だけが枠で囲われているため、分かりやすい
私はこちらのほうが良いともいました。
（特に前回の続きがない場合は、カードが縦に連続してちょっとカッコ悪いかなと思いました）

あと、もう少しだけ見やすくするとしたら、以下の点ですかね。
-  カードとカードの間に余白を入れる
-  ２つのカードに違いを出すため、異なるカラーリングにする(背景 or ボーダー）

（参考）https://getbootstrap.jp/docs/4.2/components/card/#border

※bootstrapのコンポーネントは、おしゃれではない（よくダサいと言われる）ですが、使いやすいので、その中でちょっと一工夫入れるだけ見やすさ、使いやすさは格段に上がると思います。

2021-01-31 09:24 UTC, nakamitsu-nozomi reviewed
<img width="1440" alt="スクリーンショット 2021-01-31 18 20 41" src="https://user-images.githubusercontent.com/67478234/106379746-7bc97300-63f1-11eb-81b0-795675d4a7a6.png">

一提案ですが、このようにするのはどうでしょうか。

2021-01-31 16:25 UTC, domi10momo commented
@nakamitsu-nozomi 
デザイン案ありがとうございます。縦に並んでるので見やすいですね！
nozomiさんの案を取り入れたいと思います。

2021-02-07 03:53 UTC, great084 reviewed
@domi10momo 
画面デザイン良いと思います！
動作も再度確認しました。

あと以下の点だけ
- debug文を消しておいてください(rubocop 未実施？）
- 「取得ツイート上限件数」より「取得するツイートの件数」の方がわかりやすいかと。

2021-02-07 12:28 UTC, great084 approved these changes

2021-02-07 23:05 UTC, merged