Tweetモデルのテスト(Rspec)
great084/twitter_tool pull request #95
Opened 2021-01-23 07:34 UTC by domi10momo

closes #89 

## 目的・概要

tweet, repost, retweetモデルのバリデーション、アソシエーションチェックを行う。

## 実装内容

- `gem 'shoulda-matchers'`を追加（booleanの検証のため）
- tweetモデル 

1.  パラメータ正常時、各パラメータ異常時の動作チェック
2. tweet_flag, retweet_flagがtrue, falseのみ許可していることの確認

- repost, retweet, mediumモデル

1. repost, retweetレコード作成時にtweetレコードが作成されている場合のみ正常に動作すること
2. tweetレコードを削除した時に紐付け先のrepost, retweetレコードも削除されること

## 稼働確認チェック
- [ ] ローカル環境での動作確認
- [ ] rspecの実行＆エラーなし
- [ ] rubocopの実行＆コード修正

## 参考資料
- https://github.com/thoughtbot/shoulda-matchers

## 連絡事項

2021-01-24 02:30 UTC, nakamitsu-nozomi reviewed
テストが通過していることを確認しました。

「Mediumモデルであれば、tweet_id がなければ無効」「Tweetモデルであればuser_idがなければ無効」などの外部キーに関するテストも必要なのかなと感じました。

2021-01-25 11:58 UTC, domi10momo commented
@nakamitsu-nozomi 
ありがとうございます。外部キーの存在性のテストも追加しました。
ご確認お願い致します。

2021-01-26 02:14 UTC, great084 requested changes
@domi10momo 
バリデーションの検証に関して、正しく検証ができていないと思われます。
一例だけコード内にコメント記載したので、確認してください。

2021-01-26 02:14 UTC, great084 commented on spec/models/tweet_spec.rb
> +    end
このケースはuser_idがnilの場合、エラーとなることを検証するケースだと思います。
しかし、上記構文だと、`to_not  include`なのでエラー文を含まないことを検証しています。正しくはエラー分を含むことを検証すべきではないでしょうか？

ちなみに、エラー文は日本語化されており"can't be blank"ではなく、"を入力してください"になると思います。

2021-01-26 10:49 UTC, domi10momo commented on spec/models/tweet_spec.rb
> +    end
```
[5] pry(main)> @tweet.errors
=> #<ActiveModel::Errors:0x00007fb9740164b0
 @base=
  #<Tweet:0x00007fb974017270
 @base=
  #<Tweet:0x00007fb974017270
   id: nil,
   tweet_created_at: Fri, 01 Jan 2021 00:00:00 JST +09:00,
   tweet_string_id: "123456",
   text: "string",
   retweet_count: 12,
   favorite_count: 45,
   user_id: nil,
   tweet_flag: false,
   retweet_flag: false,
   created_at: nil,
   updated_at: nil>,
 @details={:user=>[{:error=>:blank}]},
 @messages={:user=>["を入力してください"]}>
```

仰っていることの理解ができました。ありがとうございます。

2021-01-26 10:52 UTC, domi10momo commented
@great084 
テストできていると勘違いしていました。ご指摘ありがとうございます。
修正しましたのでご確認お願い致します。

2021-01-27 01:36 UTC, great084 requested changes
@domi10momo 
OKです！！お疲れさまでした。

2021-01-27 01:37 UTC, great084 approved these changes

2021-01-27 10:39 UTC, merged